#!/bin/bash
#g++ -O3  -Wall -I"/usr/local/include" cdqmc.cpp  -ljsoncpp -DEIGEN_USE_BLAS /usr/local/lib/libblis-mt.a  -fopenmp -o cdqmc 
g++ -O3  -Wall cdqmc.cpp  -ljsoncpp -DEIGEN_USE_BLAS -lblas -llapack  -fopenmp -o cdqmc 
